// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file foo/v1/foo.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file foo/v1/foo.proto.
 */
export const file_foo_v1_foo: GenFile = /*@__PURE__*/
  fileDesc("ChBmb28vdjEvZm9vLnByb3RvIiEKDUZvb1NheVJlcXVlc3QSEAoIc2VudGVuY2UYASABKAkiIgoORm9vU2F5UmVzcG9uc2USEAoIc2VudGVuY2UYASABKAkyNgoKRm9vU2VydmljZRIoCgNTYXkSDi5Gb29TYXlSZXF1ZXN0Gg8uRm9vU2F5UmVzcG9uc2UiAGIGcHJvdG8z");

/**
 * @generated from message FooSayRequest
 */
export type FooSayRequest = Message<"FooSayRequest"> & {
  /**
   * @generated from field: string sentence = 1;
   */
  sentence: string;
};

/**
 * Describes the message FooSayRequest.
 * Use `create(FooSayRequestSchema)` to create a new message.
 */
export const FooSayRequestSchema: GenMessage<FooSayRequest> = /*@__PURE__*/
  messageDesc(file_foo_v1_foo, 0);

/**
 * @generated from message FooSayResponse
 */
export type FooSayResponse = Message<"FooSayResponse"> & {
  /**
   * @generated from field: string sentence = 1;
   */
  sentence: string;
};

/**
 * Describes the message FooSayResponse.
 * Use `create(FooSayResponseSchema)` to create a new message.
 */
export const FooSayResponseSchema: GenMessage<FooSayResponse> = /*@__PURE__*/
  messageDesc(file_foo_v1_foo, 1);

/**
 * @generated from service FooService
 */
export const FooService: GenService<{
  /**
   * @generated from rpc FooService.Say
   */
  say: {
    methodKind: "unary";
    input: typeof FooSayRequestSchema;
    output: typeof FooSayResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_foo_v1_foo, 0);

