// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file bar/v1/bar.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bar/v1/bar.proto.
 */
export const file_bar_v1_bar: GenFile = /*@__PURE__*/
  fileDesc("ChBiYXIvdjEvYmFyLnByb3RvIiEKDUJhclNheVJlcXVlc3QSEAoIc2VudGVuY2UYASABKAkiIgoOQmFyU2F5UmVzcG9uc2USEAoIc2VudGVuY2UYAiABKAkyNgoKQmFyU2VydmljZRIoCgNTYXkSDi5CYXJTYXlSZXF1ZXN0Gg8uQmFyU2F5UmVzcG9uc2UiAGIGcHJvdG8z");

/**
 * @generated from message BarSayRequest
 */
export type BarSayRequest = Message<"BarSayRequest"> & {
  /**
   * @generated from field: string sentence = 1;
   */
  sentence: string;
};

/**
 * Describes the message BarSayRequest.
 * Use `create(BarSayRequestSchema)` to create a new message.
 */
export const BarSayRequestSchema: GenMessage<BarSayRequest> = /*@__PURE__*/
  messageDesc(file_bar_v1_bar, 0);

/**
 * @generated from message BarSayResponse
 */
export type BarSayResponse = Message<"BarSayResponse"> & {
  /**
   * @generated from field: string sentence = 2;
   */
  sentence: string;
};

/**
 * Describes the message BarSayResponse.
 * Use `create(BarSayResponseSchema)` to create a new message.
 */
export const BarSayResponseSchema: GenMessage<BarSayResponse> = /*@__PURE__*/
  messageDesc(file_bar_v1_bar, 1);

/**
 * @generated from service BarService
 */
export const BarService: GenService<{
  /**
   * @generated from rpc BarService.Say
   */
  say: {
    methodKind: "unary";
    input: typeof BarSayRequestSchema;
    output: typeof BarSayResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bar_v1_bar, 0);

