// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file test/v1/test.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test/v1/test.proto.
 */
export const file_test_v1_test: GenFile = /*@__PURE__*/
  fileDesc("ChJ0ZXN0L3YxL3Rlc3QucHJvdG8iJwoTVGVzdFdvcmRzU2F5UmVxdWVzdBIQCghzZW50ZW5jZRgBIAEoCSIoChRUZXN0V29yZHNTYXlSZXNwb25zZRIQCghzZW50ZW5jZRgBIAEoCTJIChBUZXN0V29yZHNTZXJ2aWNlEjQKA1NheRIULlRlc3RXb3Jkc1NheVJlcXVlc3QaFS5UZXN0V29yZHNTYXlSZXNwb25zZSIAYgZwcm90bzM");

/**
 * @generated from message TestWordsSayRequest
 */
export type TestWordsSayRequest = Message<"TestWordsSayRequest"> & {
  /**
   * @generated from field: string sentence = 1;
   */
  sentence: string;
};

/**
 * Describes the message TestWordsSayRequest.
 * Use `create(TestWordsSayRequestSchema)` to create a new message.
 */
export const TestWordsSayRequestSchema: GenMessage<TestWordsSayRequest> = /*@__PURE__*/
  messageDesc(file_test_v1_test, 0);

/**
 * @generated from message TestWordsSayResponse
 */
export type TestWordsSayResponse = Message<"TestWordsSayResponse"> & {
  /**
   * @generated from field: string sentence = 1;
   */
  sentence: string;
};

/**
 * Describes the message TestWordsSayResponse.
 * Use `create(TestWordsSayResponseSchema)` to create a new message.
 */
export const TestWordsSayResponseSchema: GenMessage<TestWordsSayResponse> = /*@__PURE__*/
  messageDesc(file_test_v1_test, 1);

/**
 * @generated from service TestWordsService
 */
export const TestWordsService: GenService<{
  /**
   * @generated from rpc TestWordsService.Say
   */
  say: {
    methodKind: "unary";
    input: typeof TestWordsSayRequestSchema;
    output: typeof TestWordsSayResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_test_v1_test, 0);

